export const questions = [
  {key: 1, title: "¿Cuál es el tiempo de entrega?", info: "De 1 a 3 días en pedidos de hasta 25 chalecos, más el tiempo que tarde el envío en llegar (de 3 a 5 días). Agradezemos su comprensión y paciencia. Le aconsejamos que realice sus compras con anticipación en periodos vacacionales y puentes el tiempo de entrega puede ser mayor debido al gran número de pedidos."}, 
  {key: 2, title: "¿Cuánto tiempo dura un chaleco salvavidas?", info: "No hay límite de tiempo estándar, aunque el cuidado adecuado hará que dure más tiempo. Los materiales saturados de agua, materiales desgastados, olor a moho o contracción de flotabilidad indican la necesidad de reemplazo."}, 
  {key: 3, title: "¿Puedo usar un PFD para varios deportes o actividades en aguas intercontinentales?", info: "Sí, pero sólo el Tipo III PFD es aprobado para diversas actividades deportivas. El PFD Tipo V, por ejemplo, es aprobados únicamente para un deporte específico de agua."},
  {key: 4, title: "¿A partir de cuantas piezas aplica el precio de mayoreo?", info: "A partir de 25 chalecos salvavidas tienes precio de mayoreo."},
  {key: 5, title: "¿Con qué frecuencia se debe probar si funciona bien un PFD?", info: "Por lo menos una vez al año (si su uso es constante). Si esta anegado, descolorido o con fugas, un PFD debe desecharse adecuadamente y destruirse para que otra persona no utilice un modelo viejo e inservible."},
  {key: 6, title: "¿Qué es un PFD (Personal Flotation Device)?", info: "Un dispositivo de flotación personal (abreviado como PFD o DFP) también conocido como chaleco salvavidas, salvavidas, preservador de vida, cinturón de vida, salvador de vida, chaqueta de vida, flotador o traje de flotación (o en inglés como life jacket, life preserver, life belt, Mae West, life vest, life saver, cork jacket, buoyancy aid or flotation suit), es un equipo diseñado para ayudar a que el usuario pueda mantenerse a flote en el agua. El usuario puede estar consciente o inconsciente."},
  {key: 7, title: "¿Hacen entregas personales o en su local?", info: "Si previamente nos contactaste, podemos agendar la entrega de tu pedido. Entregas personales en nuestro pequeño taller del Edo. Méx. (sin costo adicional). Podrás encontrarnos aquí: Juan Colorado 120"},
  {key: 8, title: "¿Una persona que sabe nadar necesita un PFD o sólo los que no saben nadar?", info: "Todas las personas cuentan con una flotabilidad natural proporcionada por el mismo cuerpo, sin embargo, todos lo necesitan, por seguridad, los tipos I, II, III son los más seguros. La mayoría de los adultos necesitan solamente usar el TIPO III para actividades acuáticas en zonas en las que el rescate sea rápido. Proporcionan flotabilidad extra para mantenerse a flote, ayudan siempre, por lo que incluso los nadadores deben usar un PFD que les ayude a salir rápidamente del agua y ponerse a salvo, si quedara inconsciente, por algún motivo, el chaleco salvavidas auxiliaría en su rescate."},
  {key: 9, title: "¿Un PFD me protege de la hipotermia?", info: "La hipotermia no puede evitarse simplemente con el uso de un PFD. Un traje especial de inmersión debe ser usado bajo un PFD en aguas frías, pero la hipotermia es siempre un riesgo si se encuentra en agua helada o expuesto a un clima frío."}
]